import type { Character, GameDef } from './types'

const IMG = {
  rumi: {
    profile: 'https://r2.kpopdemon.com/gallery/huntrix/rumi/rumi-profile.jpg',
    performance: 'https://r2.kpopdemon.com/gallery/huntrix/rumi/rumi-performance.jpg',
    demon: 'https://r2.kpopdemon.com/gallery/huntrix/rumi/rumi-demon-form.jpg',
    roof: 'https://r2.kpopdemon.com/gallery/huntrix/rumi/rumi-on-roof.jpg',
    sword: 'https://r2.kpopdemon.com/gallery/huntrix/rumi/rumi-holding-saingeom.jpg',
    fans: 'https://r2.kpopdemon.com/gallery/battles/rumi-protecting-fans.jpg',
    kick: 'https://r2.kpopdemon.com/gallery/battles/rumi-kicking-jinu.jpg',
    concert: 'https://r2.kpopdemon.com/gallery/huntrix/rumi/rumi-concert-stage.jpg',
    smile: 'https://r2.kpopdemon.com/gallery/huntrix/rumi/rumi-smiling.jpg',
    battle: 'https://r2.kpopdemon.com/gallery/huntrix/rumi/rumi-battle-stance.jpg',
    closeup: 'https://r2.kpopdemon.com/gallery/huntrix/rumi/rumi-face-close-up.jpg',
    training: 'https://r2.kpopdemon.com/gallery/huntrix/rumi/rumi-training.jpg',
    stage2: 'https://r2.kpopdemon.com/gallery/huntrix/rumi/rumi-on-stage.jpg',
    running: 'https://r2.kpopdemon.com/gallery/huntrix/rumi/rumi-running.jpg',
    power: 'https://r2.kpopdemon.com/gallery/huntrix/rumi/rumi-power-up.jpg',
    jump: 'https://r2.kpopdemon.com/gallery/huntrix/rumi/rumi-jumping.jpg',
    promo: 'https://r2.kpopdemon.com/gallery/huntrix/rumi/rumi-promo-shoot.jpg',
    victory: 'https://r2.kpopdemon.com/gallery/huntrix/rumi/rumi-victory-pose.jpg',
    singing: 'https://r2.kpopdemon.com/gallery/huntrix/rumi/rumi-singing.jpg',
    microphone: 'https://r2.kpopdemon.com/gallery/huntrix/rumi/rumi-holding-mic.jpg',
    group: 'https://r2.kpopdemon.com/gallery/huntrix/rumi/rumi-with-group.jpg',
    casual: 'https://r2.kpopdemon.com/gallery/huntrix/rumi/rumi-casual.jpg',
    dramatic: 'https://r2.kpopdemon.com/gallery/huntrix/rumi/rumi-dramatic-look.jpg',
    poster: 'https://r2.kpopdemon.com/gallery/huntrix/rumi/rumi-movie-poster.jpg',
    action: 'https://r2.kpopdemon.com/gallery/huntrix/rumi/rumi-action-shot.jpg',
  },
  mira: {
    profile: 'https://r2.kpopdemon.com/gallery/huntrix/mira/mira-profile.jpg',
    dance: 'https://r2.kpopdemon.com/gallery/huntrix/mira/mira-dance.jpg',
    weapon: 'https://r2.kpopdemon.com/gallery/huntrix/mira/mira-holding-woldo.jpg',
    stool: 'https://r2.kpopdemon.com/gallery/huntrix/mira/mira-dancing-on-stool.jpg',
    concert: 'https://r2.kpopdemon.com/gallery/huntrix/mira/mira-concert.jpg',
    battle: 'https://r2.kpopdemon.com/gallery/huntrix/mira/mira-battle.jpg',
    closeup: 'https://r2.kpopdemon.com/gallery/huntrix/mira/mira-face-close-up.jpg',
    stage: 'https://r2.kpopdemon.com/gallery/huntrix/mira/mira-on-stage.jpg',
    promo: 'https://r2.kpopdemon.com/gallery/huntrix/mira/mira-promo-shoot.jpg',
    smile: 'https://r2.kpopdemon.com/gallery/huntrix/mira/mira-smiling.jpg',
    jump: 'https://r2.kpopdemon.com/gallery/huntrix/mira/mira-jumping.jpg',
    kick: 'https://r2.kpopdemon.com/gallery/huntrix/mira/mira-high-kick.jpg',
    performance: 'https://r2.kpopdemon.com/gallery/huntrix/mira/mira-performance.jpg',
    running: 'https://r2.kpopdemon.com/gallery/huntrix/mira/mira-running.jpg',
    training: 'https://r2.kpopdemon.com/gallery/huntrix/mira/mira-training.jpg',
    victory: 'https://r2.kpopdemon.com/gallery/huntrix/mira/mira-victory.jpg',
    dramatic: 'https://r2.kpopdemon.com/gallery/huntrix/mira/mira-dramatic.jpg',
    roof: 'https://r2.kpopdemon.com/gallery/huntrix/mira/mira-on-roof.jpg',
    singing: 'https://r2.kpopdemon.com/gallery/huntrix/mira/mira-singing.jpg',
    power: 'https://r2.kpopdemon.com/gallery/huntrix/mira/mira-power-up.jpg',
    casual: 'https://r2.kpopdemon.com/gallery/huntrix/mira/mira-casual.jpg',
    poster: 'https://r2.kpopdemon.com/gallery/huntrix/mira/mira-movie-poster.jpg',
    action: 'https://r2.kpopdemon.com/gallery/huntrix/mira/mira-action.jpg',
    microphone: 'https://r2.kpopdemon.com/gallery/huntrix/mira/mira-holding-mic.jpg',
    group: 'https://r2.kpopdemon.com/gallery/huntrix/mira/mira-with-group.jpg',
  },
  zoey: {
    profile: 'https://r2.kpopdemon.com/gallery/huntrix/zoey/zoey-profile.jpg',
    performance: 'https://r2.kpopdemon.com/gallery/huntrix/zoey/zoey-performance.jpg',
    stage: 'https://r2.kpopdemon.com/gallery/huntrix/zoey/zoey-singing-on-stage.jpg',
    closeup: 'https://r2.kpopdemon.com/gallery/huntrix/zoey/zoey-face-close-up.jpg',
    determined: 'https://r2.kpopdemon.com/gallery/huntrix/zoey/zoey-looks-forward-with-determined-look.jpg',
    concert: 'https://r2.kpopdemon.com/gallery/huntrix/zoey/zoey-concert.jpg',
    battle: 'https://r2.kpopdemon.com/gallery/huntrix/zoey/zoey-battle.jpg',
    rap: 'https://r2.kpopdemon.com/gallery/huntrix/zoey/zoey-rapping.jpg',
    smile: 'https://r2.kpopdemon.com/gallery/huntrix/zoey/zoey-smiling.jpg',
    promo: 'https://r2.kpopdemon.com/gallery/huntrix/zoey/zoey-promo-shoot.jpg',
    jump: 'https://r2.kpopdemon.com/gallery/huntrix/zoey/zoey-jumping.jpg',
    training: 'https://r2.kpopdemon.com/gallery/huntrix/zoey/zoey-training.jpg',
    weapon: 'https://r2.kpopdemon.com/gallery/huntrix/zoey/zoey-holding-weapon.jpg',
    roof: 'https://r2.kpopdemon.com/gallery/huntrix/zoey/zoey-on-roof.jpg',
    running: 'https://r2.kpopdemon.com/gallery/huntrix/zoey/zoey-running.jpg',
    dance: 'https://r2.kpopdemon.com/gallery/huntrix/zoey/zoey-dancing.jpg',
    victory: 'https://r2.kpopdemon.com/gallery/huntrix/zoey/zoey-victory.jpg',
    dramatic: 'https://r2.kpopdemon.com/gallery/huntrix/zoey/zoey-dramatic.jpg',
    microphone: 'https://r2.kpopdemon.com/gallery/huntrix/zoey/zoey-holding-mic.jpg',
    power: 'https://r2.kpopdemon.com/gallery/huntrix/zoey/zoey-power-up.jpg',
    casual: 'https://r2.kpopdemon.com/gallery/huntrix/zoey/zoey-casual.jpg',
    poster: 'https://r2.kpopdemon.com/gallery/huntrix/zoey/zoey-movie-poster.jpg',
    action: 'https://r2.kpopdemon.com/gallery/huntrix/zoey/zoey-action.jpg',
    group: 'https://r2.kpopdemon.com/gallery/huntrix/zoey/zoey-with-group.jpg',
    singing: 'https://r2.kpopdemon.com/gallery/huntrix/zoey/zoey-singing.jpg',
  },
  group: {
    official: 'https://r2.kpopdemon.com/gallery/huntrix/huntrix-group-official.jpg',
    performance: 'https://r2.kpopdemon.com/gallery/huntrix/huntrix-group-performance.jpg',
    bathhouse: 'https://r2.kpopdemon.com/gallery/huntrix/huntrix-bathhouse.jpg',
    noodles: 'https://r2.kpopdemon.com/gallery/huntrix/huntrix-instant-noodles.jpg',
    stage: 'https://r2.kpopdemon.com/gallery/huntrix/huntrix-on-stage.jpg',
    soundtrack: 'https://r2.kpopdemon.com/gallery/albums/huntrix-soundtrack.jpg',
    poster: 'https://r2.kpopdemon.com/gallery/huntrix/huntrix-movie-poster.jpg',
    promo: 'https://r2.kpopdemon.com/gallery/huntrix/huntrix-promo.jpg',
    concert: 'https://r2.kpopdemon.com/gallery/huntrix/huntrix-concert.jpg',
    training: 'https://r2.kpopdemon.com/gallery/huntrix/huntrix-training.jpg',
  },
}

export const CHARS: Character[] = [
  { id:'rumi', name:'ルミ', nameEn:'RUMI', role:'リーダー', emoji:'👑', color:'#C084FC', dark:'#6D28D9', light:'#F3E8FF', bg:'linear-gradient(160deg,#0f0720 0%,#2a0855 55%,#5b21b6 100%)', img:IMG.rumi, desc:'つよくてやさしいリーダー！' },
  { id:'mira', name:'ミラ', nameEn:'MIRA', role:'ダンサー', emoji:'🔥', color:'#FB7185', dark:'#BE123C', light:'#FFF1F2', bg:'linear-gradient(160deg,#1c0507 0%,#4c0519 55%,#9f1239 100%)', img:IMG.mira, desc:'おどりのてんさいダンサー！' },
  { id:'zoey', name:'ゾーイ', nameEn:'ZOEY', role:'ラッパー', emoji:'🎤', color:'#38BDF8', dark:'#0369A1', light:'#E0F2FE', bg:'linear-gradient(160deg,#020c1a 0%,#0c2d4c 55%,#075985 100%)', img:IMG.zoey, desc:'クールでかわいいラッパー！' },
]

export const CHAR_IMAGES: Record<string, string[]> = {
  rumi: Object.values(IMG.rumi),
  mira: Object.values(IMG.mira),
  zoey: Object.values(IMG.zoey),
}

export const ALL_IMAGES: string[] = [
  ...Object.values(IMG.rumi),
  ...Object.values(IMG.mira),
  ...Object.values(IMG.zoey),
  ...Object.values(IMG.group),
]

export const GAMES: GameDef[] = [
  { id:'starCatch',    label:'スターキャッチ',   emoji:'⭐', desc:'落ちてくる星をタップ！' },
  { id:'demonShoot',  label:'デーモンシュート',  emoji:'🗡️', desc:'悪魔をたおせ！キャラはさけて' },
  { id:'rhythmTap',   label:'リズムタップ',      emoji:'🎵', desc:'ビートにのってタップ！' },
  { id:'memoryCards', label:'メモリーカード',    emoji:'🃏', desc:'おなじカードをさがそう！' },
  { id:'ballCatch',   label:'ボールキャッチ',   emoji:'🏀', desc:'ゆびをうごかしてキャッチ！' },
  { id:'quickDraw',   label:'クイックドロー',   emoji:'🔔', desc:'シグナルがでたらすぐタップ！' },
  { id:'janken',      label:'じゃんけん',        emoji:'✊', desc:'キャラクターとじゃんけん勝負！' },
  { id:'numberTouch', label:'ナンバータッチ',   emoji:'🔢', desc:'1からじゅんにタップ！' },
  { id:'bubblePop',   label:'バブルポップ',      emoji:'🫧', desc:'うかぶバブルをはじこう！' },
  { id:'hideSeek',    label:'かくれんぼ',        emoji:'👀', desc:'でてきたらすぐタップ！' },
  { id:'puzzle',      label:'パズル',            emoji:'🧩', desc:'しゃしんをあわせよう！' },
  { id:'simonSays',   label:'サイモンセズ',      emoji:'🎮', desc:'おなじじゅんばんでタップ！' },
  { id:'slot',        label:'スロット',           emoji:'🎰', desc:'キャラをそろえよう！' },
  { id:'speedTap',    label:'スピードタップ',    emoji:'⚡', desc:'できるだけはやくタップ！' },
  { id:'movingTarget',label:'的当て',             emoji:'🎯', desc:'ちょうどいいときにタップ！' },
  { id:'demonAvoid',  label:'デーモンアボイド',  emoji:'🏃', desc:'デーモンをよけろ！' },
  { id:'photoSnap',   label:'フォトスナップ',    emoji:'📸', desc:'いいしゃしんをとろう！' },
  { id:'snake',       label:'スネーク',          emoji:'🐍', desc:'えさをたべてながくなれ！' },
  { id:'towerStack',  label:'タワースタック',    emoji:'🏗️', desc:'ブロックをつみあげよう！' },
  { id:'typeRace',    label:'タイプバトル',       emoji:'⌨️', desc:'もじをうってデーモンをたおせ！' },
  { id:'colorMatch',  label:'カラーマッチ',       emoji:'🎨', desc:'いろをあわせてタップ！' },
  { id:'dashDodge',   label:'ダッシュドッジ',     emoji:'🌪️', desc:'デーモンをかわしてにげろ！' },
  { id:'spaceShooter', label:'スペースシューター', emoji:'🚀', desc:'宇宙船で敵をうちおとせ！' },
  { id:'pongGame',     label:'ポンゲーム',          emoji:'🏓', desc:'AIとポン対決！' },
  { id:'flappyChar',   label:'フラッピーキャラ',    emoji:'🐦', desc:'スペースで羽ばたいて！' },
  { id:'brickBreaker', label:'ブロック崩し',         emoji:'🧱', desc:'全部のブロックをくずせ！' },
  { id:'mathBlitz',    label:'計算バトル',           emoji:'🧮', desc:'計算をとかしてデーモンにかつ！' },
  { id:'whackMole',    label:'デーモンたたき',       emoji:'🔨', desc:'でてきたデーモンをたたけ！' },
  { id:'wordScramble', label:'ワードスクランブル',   emoji:'🔤', desc:'バラバラの文字をならべよう！' },
  { id:'reflexTest',   label:'リフレックス',         emoji:'⚡', desc:'シグナルにすばやくはんのう！' },
  { id:'ticTacToe',    label:'三目並べ',             emoji:'⭕', desc:'AIに勝って3つそろえろ！' },
  { id:'catchOrder',   label:'キャッチオーダー',     emoji:'🎯', desc:'じゅんばんにタッチ！' },
  { id:'higherLower',  label:'ハイアーロワー',        emoji:'🔢', desc:'数字をよそくしてあてよう！' },
  { id:'oddOneOut',    label:'なかまはずれ',           emoji:'🔍', desc:'ちがうえもじをみつけろ！' },
  { id:'targetBlast',  label:'ターゲットブラスト',    emoji:'💥', desc:'せまるまえにタップ！' },
  { id:'gravityFlip',  label:'グラビティフリップ',    emoji:'⬆️', desc:'じゅうりょくをきりかえろ！' },
  { id:'endlessRun',   label:'エンドレスラン',         emoji:'🏃', desc:'かべをこえてはしれ！' },
  { id:'bombDefuse',   label:'ばくだんかいじょ',       emoji:'💣', desc:'じゅんばんにタップしてかいじょ！' },
  { id:'spinTarget',   label:'スピンターゲット',       emoji:'🎯', desc:'みどりゾーンでとめろ！' },
  { id:'numberRain',   label:'ナンバーレイン',         emoji:'🌧️', desc:'たす数をあわせよう！' },
  { id:'ghostChase',   label:'ゴーストチェイス',       emoji:'👻', desc:'ゆうれいをつかまえろ！' },
  { id:'powerShot',    label:'パワーショット',         emoji:'🔫', desc:'パワーをちょうせつしてシュート！' },
  { id:'tileSweep',    label:'タイルスイープ',         emoji:'🃏', desc:'ぜんぶのタイルをめくれ！' },
  { id:'laserDodge',   label:'レーザードッジ',         emoji:'⚡', desc:'レーザーをよけてサバイバル！' },
  { id:'demonicSort',  label:'デーモンソート',         emoji:'😈', desc:'あくとぜんをわけろ！' },
  { id:'shadowMatch',  label:'シャドウマッチ',         emoji:'🌑', desc:'かげにあうものをえらべ！' },
  { id:'tapRhythm',    label:'タップリズム',           emoji:'🎶', desc:'ビートにあわせてタップ！' },
  { id:'colorStop',    label:'カラーストップ',         emoji:'🎨', desc:'もくひょうのいろでとめよう！' },
  { id:'iconFlash',    label:'アイコンフラッシュ',     emoji:'👁️', desc:'ひかったえもじをおぼえろ！' },
  { id:'chainBomb',    label:'チェーンボム',           emoji:'⛓️', desc:'すばやくタップしてチェーン！' },
  { id:'asteroidRun',  label:'アステロイドラン',       emoji:'☄️', desc:'いんせきをよけてサバイバル！' },
  { id:'rocketBoost',  label:'ロケットブースト',       emoji:'🚀', desc:'ブーストしてかべをくぐれ！' },
]
