/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
      },
      borderRadius: { lg: "var(--radius)", md: "calc(var(--radius) - 2px)", sm: "calc(var(--radius) - 4px)" },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "float": { "0%,100%": { transform: "translateY(0px)" }, "50%": { transform: "translateY(-12px)" } },
        "glow-pulse": { "0%,100%": { opacity: "0.8" }, "50%": { opacity: "1" } },
        "pop-in": { "0%": { transform: "scale(0)", opacity: "0" }, "80%": { transform: "scale(1.1)" }, "100%": { transform: "scale(1)", opacity: "1" } },
        "float-up": { "0%": { transform: "translateY(0)", opacity: "1" }, "100%": { transform: "translateY(-80px)", opacity: "0" } },
        "danger-flash": { "0%": { opacity: "0.7" }, "100%": { opacity: "0" } },
        "slide-up": { from: { transform: "translateY(30px)", opacity: "0" }, to: { transform: "translateY(0)", opacity: "1" } },
        "bounce-in": { "0%": { transform: "scale(0.3)", opacity: "0" }, "60%": { transform: "scale(1.1)" }, "100%": { transform: "scale(1)", opacity: "1" } },
        "urgent": { "0%,100%": { color: "#F87171" }, "50%": { color: "#FF0000", transform: "scale(1.15)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "float": "float 3s ease-in-out infinite",
        "glow-pulse": "glow-pulse 2s ease-in-out infinite",
        "pop-in": "pop-in 0.4s cubic-bezier(0.34,1.56,0.64,1)",
        "float-up": "float-up 0.85s ease-out forwards",
        "danger-flash": "danger-flash 0.5s ease-out forwards",
        "slide-up": "slide-up 0.5s ease-out",
        "bounce-in": "bounce-in 0.5s cubic-bezier(0.34,1.56,0.64,1)",
        "urgent": "urgent 0.5s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
